# Generated by Django 5.1.2 on 2024-10-27 12:24

import regularExam.author.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[regularExam.author.validators.ExactlySixDigitsValidator()]),
        ),
    ]
